org: caiocaminha
app: jf-web-scrap
service: jf-web-scrap

frameworkVersion: '3'


provider:
  name: aws
  runtime: python3.8
  versionFunctions: false
  memorySize: 128
  region: us-east-1

functions:
  job_finder:
    handler: handler.job_finder
    events:
      # Invoke Lambda function every 2nd minute from Mon-Fri
      - schedule: cron(0 18 * * ? *)
    timeout: 500
